/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/pca/usuario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar Itens de PCA por Ano do PCA, IdUsuario e Código de Classificação Superior */
        get: operations["consultarItensPorUsuarioAno"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pca/atualizacao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar PCA por Data de Atualização Global */
        get: operations["consultarItensPorUsuarioAno_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pca/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar Itens de PCA por Ano do PCA e Código de Classificação Superior */
        get: operations["consultarItensPorAno"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orgaos/{cnpj}/compras/{ano}/{sequencial}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar Contratação */
        get: operations["consultarCompra"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/instrumentoscobranca/inclusao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar Instrumentos de Cobrança por Data de Inclusão */
        get: operations["consultarInstrumentos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contratos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar Contratos por Data de Publicação */
        get: operations["consultarContratosPorDataPublicacao"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contratos/atualizacao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar Contratos/Empenhos por Data de Atualização Global */
        get: operations["consultarContratosPorDataAtualizacaoGlobal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contratacoes/publicacao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar Contratações por Data de Publicação */
        get: operations["consultarContratacaoPorDataDePublicacao"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contratacoes/proposta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar Contratações com Recebimento de Propostas Aberto */
        get: operations["consultarContratacaoPeriodoRecebimentoPropostas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contratacoes/atualizacao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar Contratações por Data de Atualização Global */
        get: operations["consultarContratacaoPorDataUltimaAtualizacao"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/atas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar Ata de Registro de Preço por Período de Vigência */
        get: operations["consultarAtaRegistroPrecoPeriodo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/atas/atualizacao": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar Atas de Registro de Preço por Data de Atualização Global */
        get: operations["consultarAtaRegistroPrecoDataAtualizacao"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RespostaErroValidacaoDTO: {
            message?: string;
            path?: string;
            timestamp?: string;
            status?: string;
            error?: string;
        };
        PaginaRetornoPlanoContratacaoComItensDoUsuarioDTO: {
            data?: components["schemas"]["PlanoContratacaoComItensDoUsuarioDTO"][];
            /** Format: int64 */
            totalRegistros?: number;
            /** Format: int64 */
            totalPaginas?: number;
            /** Format: int64 */
            numeroPagina?: number;
            /** Format: int64 */
            paginasRestantes?: number;
            empty?: boolean;
        };
        PlanoContratacaoComItensDoUsuarioDTO: {
            itens?: components["schemas"]["PlanoContratacaoItemDTO"][];
            codigoUnidade?: string;
            nomeUnidade?: string;
            /** Format: int32 */
            anoPca?: number;
            idPcaPncp?: string;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            dataPublicacaoPNCP?: string;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            dataAtualizacaoGlobalPCA?: string;
            orgaoEntidadeCnpj?: string;
            orgaoEntidadeRazaoSocial?: string;
        };
        PlanoContratacaoItemDTO: {
            descricaoItem?: string;
            /** Format: int64 */
            classificacaoCatalogoId?: number;
            categoriaItemPcaNome?: string;
            nomeClassificacaoCatalogo?: string;
            quantidadeEstimada?: number;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            dataInclusao?: string;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            dataAtualizacao?: string;
            /** Format: int32 */
            numeroItem?: number;
            valorUnitario?: number;
            valorTotal?: number;
            classificacaoSuperiorNome?: string;
            pdmCodigo?: string;
            pdmDescricao?: string;
            codigoItem?: string;
            unidadeFornecimento?: string;
            valorOrcamentoExercicio?: number;
            unidadeRequisitante?: string;
            /** Format: date */
            dataDesejada?: string;
            grupoContratacaoCodigo?: string;
            grupoContratacaoNome?: string;
            classificacaoSuperiorCodigo?: string;
        };
        ContratacaoFonteOrcamentariaDTO: {
            /** Format: int64 */
            codigo?: number;
            nome?: string;
            descricao?: string;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            dataInclusao?: string;
        };
        RecuperarAmparoLegalDTO: {
            nome?: string;
            descricao?: string;
            /** Format: int64 */
            codigo?: number;
        };
        RecuperarCompraDTO: {
            valorTotalEstimado?: number;
            valorTotalHomologado?: number;
            /** @enum {string} */
            indicadorOrcamentoSigiloso?: "COMPRA_SEM_SIGILO" | "COMPRA_PARCIALMENTE_SIGILOSA" | "COMPRA_TOTALMENTE_SIGILOSA";
            /** Format: int32 */
            orcamentoSigilosoCodigo?: number;
            orcamentoSigilosoDescricao?: string;
            numeroControlePNCP?: string;
            linkSistemaOrigem?: string;
            linkProcessoEletronico?: string;
            /** Format: int32 */
            anoCompra?: number;
            /** Format: int32 */
            sequencialCompra?: number;
            numeroCompra?: string;
            processo?: string;
            orgaoEntidade?: components["schemas"]["RecuperarOrgaoEntidadeDTO"];
            unidadeOrgao?: components["schemas"]["RecuperarUnidadeOrgaoDTO"];
            orgaoSubRogado?: components["schemas"]["RecuperarOrgaoEntidadeDTO"];
            unidadeSubRogada?: components["schemas"]["RecuperarUnidadeOrgaoDTO"];
            /** Format: int64 */
            modalidadeId?: number;
            modalidadeNome?: string;
            justificativaPresencial?: string;
            /** Format: int64 */
            modoDisputaId?: number;
            modoDisputaNome?: string;
            /** Format: int64 */
            tipoInstrumentoConvocatorioCodigo?: number;
            tipoInstrumentoConvocatorioNome?: string;
            amparoLegal?: components["schemas"]["RecuperarAmparoLegalDTO"];
            objetoCompra?: string;
            informacaoComplementar?: string;
            srp?: boolean;
            fontesOrcamentarias?: components["schemas"]["ContratacaoFonteOrcamentariaDTO"][];
            emendaParlamentar?: boolean;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            dataPublicacaoPncp?: string;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            dataAberturaProposta?: string;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            dataEncerramentoProposta?: string;
            /** @enum {string} */
            situacaoCompraId?: "1" | "2" | "3" | "4";
            situacaoCompraNome?: string;
            existeResultado?: boolean;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            dataInclusao?: string;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            dataAtualizacao?: string;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            dataAtualizacaoGlobal?: string;
            usuarioNome?: string;
        };
        RecuperarOrgaoEntidadeDTO: {
            cnpj?: string;
            razaoSocial?: string;
            poderId?: string;
            esferaId?: string;
        };
        RecuperarUnidadeOrgaoDTO: {
            ufNome?: string;
            ufSigla?: string;
            municipioNome?: string;
            codigoUnidade?: string;
            nomeUnidade?: string;
            codigoIbge?: string;
        };
        Categoria: {
            /** Format: int64 */
            id?: number;
            nome?: string;
        };
        ConsultarInstrumentoCobrancaDTO: {
            cnpj?: string;
            /** Format: int32 */
            ano?: number;
            /** Format: int32 */
            sequencialContrato?: number;
            /** Format: int32 */
            sequencialInstrumentoCobranca?: number;
            tipoInstrumentoCobranca?: components["schemas"]["TipoInstrumentoCobrancaDTO"];
            numeroInstrumentoCobranca?: string;
            /** Format: date */
            dataEmissaoDocumento?: string;
            observacao?: string;
            chaveNFe?: string;
            /** Format: int64 */
            fonteNFe?: number;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            dataConsultaNFe?: string;
            statusResponseNFe?: string;
            jsonResponseNFe?: string;
            notaFiscalEletronica?: components["schemas"]["NotaFiscalEletronicaConsultaDTO"];
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            dataInclusao?: string;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            dataAtualizacao?: string;
            recuperarContratoDTO?: components["schemas"]["RecuperarContratoDTO"];
        };
        EventoNotaFiscalConsultaDTO: {
            dataEvento?: string;
            tipoEvento?: string;
            evento?: string;
            motivoEvento?: string;
        };
        ItemNotaFiscalConsultaDTO: {
            numeroItem?: string;
            descricaoProdutoServico?: string;
            codigoNCM?: string;
            descricaoNCM?: string;
            cfop?: string;
            quantidade?: string;
            unidade?: string;
            valorUnitario?: string;
            valorTotal?: string;
        };
        NotaFiscalEletronicaConsultaDTO: {
            /** Format: int64 */
            instrumentoCobrancaId?: number;
            chave?: string;
            /** Format: int64 */
            nfTransparenciaID?: number;
            /** Format: int64 */
            numero?: number;
            /** Format: int32 */
            serie?: number;
            dataEmissao?: string;
            niEmitente?: string;
            nomeEmitente?: string;
            nomeMunicipioEmitente?: string;
            codigoOrgaoDestinatario?: string;
            nomeOrgaoDestinatario?: string;
            codigoOrgaoSuperiorDestinatario?: string;
            nomeOrgaoSuperiorDestinatario?: string;
            valorNotaFiscal?: string;
            tipoEventoMaisRecente?: string;
            dataTipoEventoMaisRecente?: string;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            dataInclusao?: string;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            dataAtualizacao?: string;
            itens?: components["schemas"]["ItemNotaFiscalConsultaDTO"][];
            eventos?: components["schemas"]["EventoNotaFiscalConsultaDTO"][];
        };
        PaginaRetornoConsultarInstrumentoCobrancaDTO: {
            data?: components["schemas"]["ConsultarInstrumentoCobrancaDTO"][];
            /** Format: int64 */
            totalRegistros?: number;
            /** Format: int64 */
            totalPaginas?: number;
            /** Format: int64 */
            numeroPagina?: number;
            /** Format: int64 */
            paginasRestantes?: number;
            empty?: boolean;
        };
        RecuperarContratoDTO: {
            numeroControlePncpAta?: string;
            codigoPaisFornecedor?: string;
            numeroControlePncpCompra?: string;
            orgaoEntidade?: components["schemas"]["RecuperarOrgaoEntidadeDTO"];
            /** Format: int32 */
            anoContrato?: number;
            /** Format: int32 */
            sequencialContrato?: number;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            dataAtualizacao?: string;
            emendaParlamentar?: boolean;
            processo?: string;
            informacaoComplementar?: string;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            dataPublicacaoPncp?: string;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            dataAtualizacaoGlobal?: string;
            unidadeOrgao?: components["schemas"]["RecuperarUnidadeOrgaoDTO"];
            orgaoSubRogado?: components["schemas"]["RecuperarOrgaoEntidadeDTO"];
            unidadeSubRogada?: components["schemas"]["RecuperarUnidadeOrgaoDTO"];
            receita?: boolean;
            /** Format: int32 */
            numeroParcelas?: number;
            /** Format: int32 */
            numeroRetificacao?: number;
            temRemanejamento?: boolean;
            frutoAdesao?: boolean;
            tipoContrato?: components["schemas"]["TipoContrato"];
            numeroContratoEmpenho?: string;
            categoriaProcesso?: components["schemas"]["Categoria"];
            /** @enum {string} */
            tipoPessoaSubContratada?: "PJ" | "PF" | "PE";
            niFornecedorSubContratado?: string;
            nomeFornecedorSubContratado?: string;
            objetoContrato?: string;
            valorInicial?: number;
            valorParcela?: number;
            valorGlobal?: number;
            valorAcumulado?: number;
            /** Format: date */
            dataAssinatura?: string;
            /** Format: date */
            dataVigenciaInicio?: string;
            /** Format: date */
            dataVigenciaFim?: string;
            identificadorCipi?: string;
            urlCipi?: string;
            /** @enum {string} */
            tipoPessoa?: "PJ" | "PF" | "PE";
            niFornecedor?: string;
            nomeRazaoSocialFornecedor?: string;
            numeroControlePNCP?: string;
            usuarioNome?: string;
        };
        TipoContrato: {
            /** Format: int64 */
            id?: number;
            nome?: string;
        };
        TipoInstrumentoCobrancaDTO: {
            /** Format: int64 */
            id?: number;
            nome?: string;
            descricao?: string;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            dataInclusao?: string;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            dataAtualizacao?: string;
            statusAtivo?: boolean;
        };
        PaginaRetornoRecuperarContratoDTO: {
            data?: components["schemas"]["RecuperarContratoDTO"][];
            /** Format: int64 */
            totalRegistros?: number;
            /** Format: int64 */
            totalPaginas?: number;
            /** Format: int64 */
            numeroPagina?: number;
            /** Format: int64 */
            paginasRestantes?: number;
            empty?: boolean;
        };
        PaginaRetornoRecuperarCompraPublicacaoDTO: {
            data?: components["schemas"]["RecuperarCompraPublicacaoDTO"][];
            /** Format: int64 */
            totalRegistros?: number;
            /** Format: int64 */
            totalPaginas?: number;
            /** Format: int64 */
            numeroPagina?: number;
            /** Format: int64 */
            paginasRestantes?: number;
            empty?: boolean;
        };
        RecuperarCompraPublicacaoDTO: {
            orgaoEntidade?: components["schemas"]["RecuperarOrgaoEntidadeDTO"];
            valorTotalHomologado?: number;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            dataInclusao?: string;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            dataAtualizacao?: string;
            /** Format: int32 */
            anoCompra?: number;
            srp?: boolean;
            /** Format: int32 */
            sequencialCompra?: number;
            emendaParlamentar?: boolean;
            numeroCompra?: string;
            processo?: string;
            objetoCompra?: string;
            informacaoComplementar?: string;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            dataAberturaProposta?: string;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            dataEncerramentoProposta?: string;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            dataPublicacaoPncp?: string;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            dataAtualizacaoGlobal?: string;
            unidadeOrgao?: components["schemas"]["RecuperarUnidadeOrgaoDTO"];
            orgaoSubRogado?: components["schemas"]["RecuperarOrgaoEntidadeDTO"];
            unidadeSubRogada?: components["schemas"]["RecuperarUnidadeOrgaoDTO"];
            numeroControlePNCP?: string;
            amparoLegal?: components["schemas"]["RecuperarAmparoLegalDTO"];
            linkSistemaOrigem?: string;
            linkProcessoEletronico?: string;
            justificativaPresencial?: string;
            valorTotalEstimado?: number;
            /** Format: int64 */
            modalidadeId?: number;
            modalidadeNome?: string;
            /** Format: int64 */
            modoDisputaId?: number;
            modoDisputaNome?: string;
            /** Format: int64 */
            tipoInstrumentoConvocatorioCodigo?: number;
            tipoInstrumentoConvocatorioNome?: string;
            fontesOrcamentarias?: components["schemas"]["ContratacaoFonteOrcamentariaDTO"][];
            /** @enum {string} */
            situacaoCompraId?: "1" | "2" | "3" | "4";
            situacaoCompraNome?: string;
            usuarioNome?: string;
        };
        AtaRegistroPrecoPeriodoDTO: {
            numeroControlePNCPAta?: string;
            numeroAtaRegistroPreco?: string;
            /** Format: int32 */
            anoAta?: number;
            numeroControlePNCPCompra?: string;
            cancelado?: boolean;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            dataCancelamento?: string;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            dataAssinatura?: string;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            vigenciaInicio?: string;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            vigenciaFim?: string;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            dataPublicacaoPncp?: string;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            dataInclusao?: string;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            dataAtualizacao?: string;
            /**
             * Format: date-time
             * @example 2026-10-04T10:30:00
             */
            dataAtualizacaoGlobal?: string;
            usuario?: string;
            objetoContratacao?: string;
            cnpjOrgao?: string;
            nomeOrgao?: string;
            cnpjOrgaoSubrogado?: string;
            nomeOrgaoSubrogado?: string;
            codigoUnidadeOrgao?: string;
            nomeUnidadeOrgao?: string;
            codigoUnidadeOrgaoSubrogado?: string;
            nomeUnidadeOrgaoSubrogado?: string;
            possibilidadeAdesao?: boolean;
        };
        PaginaRetornoAtaRegistroPrecoPeriodoDTO: {
            data?: components["schemas"]["AtaRegistroPrecoPeriodoDTO"][];
            /** Format: int64 */
            totalRegistros?: number;
            /** Format: int64 */
            totalPaginas?: number;
            /** Format: int64 */
            numeroPagina?: number;
            /** Format: int64 */
            paginasRestantes?: number;
            empty?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    consultarItensPorUsuarioAno: {
        parameters: {
            query: {
                anoPca: number;
                idUsuario: number;
                codigoClassificacaoSuperior?: string;
                cnpj?: string;
                pagina: number;
                tamanhoPagina?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PaginaRetornoPlanoContratacaoComItensDoUsuarioDTO"];
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    } | components["schemas"]["RespostaErroValidacaoDTO"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    consultarItensPorUsuarioAno_1: {
        parameters: {
            query: {
                /** @description Formato: yyyyMMdd */
                dataInicio: string;
                /** @description Formato: yyyyMMdd */
                dataFim: string;
                cnpj?: string;
                codigoUnidade?: string;
                pagina: number;
                tamanhoPagina?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PaginaRetornoPlanoContratacaoComItensDoUsuarioDTO"];
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    } | components["schemas"]["RespostaErroValidacaoDTO"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    consultarItensPorAno: {
        parameters: {
            query: {
                anoPca: number;
                codigoClassificacaoSuperior: string;
                pagina: number;
                tamanhoPagina?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PaginaRetornoPlanoContratacaoComItensDoUsuarioDTO"];
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    } | components["schemas"]["RespostaErroValidacaoDTO"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    consultarCompra: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cnpj: string;
                ano: number;
                sequencial: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecuperarCompraDTO"];
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    } | components["schemas"]["RespostaErroValidacaoDTO"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    consultarInstrumentos: {
        parameters: {
            query: {
                /** @description Formato: yyyyMMdd */
                dataInicial: string;
                /** @description Formato: yyyyMMdd */
                dataFinal: string;
                tipoInstrumentoCobranca?: number;
                cnpjOrgao?: string;
                pagina: number;
                tamanhoPagina?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PaginaRetornoConsultarInstrumentoCobrancaDTO"];
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    } | components["schemas"]["RespostaErroValidacaoDTO"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    consultarContratosPorDataPublicacao: {
        parameters: {
            query: {
                /** @description Formato: yyyyMMdd */
                dataInicial: string;
                /** @description Formato: yyyyMMdd */
                dataFinal: string;
                cnpjOrgao?: string;
                codigoUnidadeAdministrativa?: string;
                usuarioId?: number;
                pagina: number;
                tamanhoPagina?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PaginaRetornoRecuperarContratoDTO"];
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    } | components["schemas"]["RespostaErroValidacaoDTO"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    consultarContratosPorDataAtualizacaoGlobal: {
        parameters: {
            query: {
                /** @description Formato: yyyyMMdd */
                dataInicial: string;
                /** @description Formato: yyyyMMdd */
                dataFinal: string;
                cnpjOrgao?: string;
                codigoUnidadeAdministrativa?: string;
                usuarioId?: number;
                pagina: number;
                tamanhoPagina?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PaginaRetornoRecuperarContratoDTO"];
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    } | components["schemas"]["RespostaErroValidacaoDTO"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    consultarContratacaoPorDataDePublicacao: {
        parameters: {
            query: {
                /** @description Formato: yyyyMMdd */
                dataInicial: string;
                /** @description Formato: yyyyMMdd */
                dataFinal: string;
                codigoModalidadeContratacao: number;
                codigoModoDisputa?: number;
                uf?: string;
                codigoMunicipioIbge?: string;
                cnpj?: string;
                codigoUnidadeAdministrativa?: string;
                idUsuario?: number;
                pagina: number;
                tamanhoPagina?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PaginaRetornoRecuperarCompraPublicacaoDTO"];
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    } | components["schemas"]["RespostaErroValidacaoDTO"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    consultarContratacaoPeriodoRecebimentoPropostas: {
        parameters: {
            query: {
                dataFinal: string;
                codigoModalidadeContratacao?: number;
                uf?: string;
                codigoMunicipioIbge?: string;
                cnpj?: string;
                codigoUnidadeAdministrativa?: string;
                idUsuario?: number;
                pagina: number;
                tamanhoPagina?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PaginaRetornoRecuperarCompraPublicacaoDTO"];
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    } | components["schemas"]["RespostaErroValidacaoDTO"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    consultarContratacaoPorDataUltimaAtualizacao: {
        parameters: {
            query: {
                /** @description Formato: yyyyMMdd */
                dataInicial: string;
                /** @description Formato: yyyyMMdd */
                dataFinal: string;
                codigoModalidadeContratacao: number;
                codigoModoDisputa?: number;
                uf?: string;
                codigoMunicipioIbge?: string;
                cnpj?: string;
                codigoUnidadeAdministrativa?: string;
                idUsuario?: number;
                pagina: number;
                tamanhoPagina?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PaginaRetornoRecuperarCompraPublicacaoDTO"];
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    } | components["schemas"]["RespostaErroValidacaoDTO"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    consultarAtaRegistroPrecoPeriodo: {
        parameters: {
            query: {
                /** @description Formato: yyyyMMdd */
                dataInicial: string;
                /** @description Formato: yyyyMMdd */
                dataFinal: string;
                idUsuario?: number;
                cnpj?: string;
                codigoUnidadeAdministrativa?: string;
                pagina: number;
                tamanhoPagina?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PaginaRetornoAtaRegistroPrecoPeriodoDTO"];
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    } | components["schemas"]["RespostaErroValidacaoDTO"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    consultarAtaRegistroPrecoDataAtualizacao: {
        parameters: {
            query: {
                /** @description Formato: yyyyMMdd */
                dataInicial: string;
                /** @description Formato: yyyyMMdd */
                dataFinal: string;
                idUsuario?: number;
                cnpj?: string;
                codigoUnidadeAdministrativa?: string;
                pagina: number;
                tamanhoPagina?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PaginaRetornoAtaRegistroPrecoPeriodoDTO"];
                };
            };
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    } | components["schemas"]["RespostaErroValidacaoDTO"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string | {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
